/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-05-10 19:39:48 UTC)
 * on 2013-05-13 at 11:19:25 UTC 
 * Modify at your own risk.
 */

package com.jman.trackrate.tracksendpoint.model;

/**
 * Model definition for Tracks.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the . For a detailed explanation see:
 * <a href="http://code.google.com/p/google-api-java-client/wiki/Json">http://code.google.com/p/google-api-java-client/wiki/Json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Tracks extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<Comments> commentset;

  static {
    // hack to force ProGuard to consider Comments used, since otherwise it would be stripped out
    // see http://code.google.com/p/google-api-java-client/issues/detail?id=528
    com.google.api.client.util.Data.nullOf(Comments.class);
  }

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private com.google.api.client.util.DateTime dateUpload;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Double distanceTravelled;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer ratingCount;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<GeoPt> route;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String trackDescription;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String trackImage;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String trackName;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer trackRating;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private User user;

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<Comments> getCommentset() {
    return commentset;
  }

  /**
   * @param commentset commentset or {@code null} for none
   */
  public Tracks setCommentset(java.util.List<Comments> commentset) {
    this.commentset = commentset;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public com.google.api.client.util.DateTime getDateUpload() {
    return dateUpload;
  }

  /**
   * @param dateUpload dateUpload or {@code null} for none
   */
  public Tracks setDateUpload(com.google.api.client.util.DateTime dateUpload) {
    this.dateUpload = dateUpload;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Double getDistanceTravelled() {
    return distanceTravelled;
  }

  /**
   * @param distanceTravelled distanceTravelled or {@code null} for none
   */
  public Tracks setDistanceTravelled(java.lang.Double distanceTravelled) {
    this.distanceTravelled = distanceTravelled;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public Tracks setId(java.lang.Long id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getRatingCount() {
    return ratingCount;
  }

  /**
   * @param ratingCount ratingCount or {@code null} for none
   */
  public Tracks setRatingCount(java.lang.Integer ratingCount) {
    this.ratingCount = ratingCount;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.util.List<GeoPt> getRoute() {
    return route;
  }

  /**
   * @param route route or {@code null} for none
   */
  public Tracks setRoute(java.util.List<GeoPt> route) {
    this.route = route;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getTrackDescription() {
    return trackDescription;
  }

  /**
   * @param trackDescription trackDescription or {@code null} for none
   */
  public Tracks setTrackDescription(java.lang.String trackDescription) {
    this.trackDescription = trackDescription;
    return this;
  }

  /**
   * @see #decodeTrackImage()
   * @return value or {@code null} for none
   */
  public java.lang.String getTrackImage() {
    return trackImage;
  }

  /**

   * @see #getTrackImage()
   * @return Base64 decoded value or {@code null} for none
   *
   * @since 1.14
   */
  public byte[] decodeTrackImage() {
    return com.google.api.client.util.Base64.decodeBase64(trackImage);
  }

  /**
   * @see #encodeTrackImage()
   * @param trackImage trackImage or {@code null} for none
   */
  public Tracks setTrackImage(java.lang.String trackImage) {
    this.trackImage = trackImage;
    return this;
  }

  /**

   * @see #setTrackImage()
   *
   * <p>
   * The value is encoded Base64 or {@code null} for none.
   * </p>
   *
   * @since 1.14
   */
  public Tracks encodeTrackImage(byte[] trackImage) {
    this.trackImage = com.google.api.client.util.Base64.encodeBase64URLSafeString(trackImage);
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getTrackName() {
    return trackName;
  }

  /**
   * @param trackName trackName or {@code null} for none
   */
  public Tracks setTrackName(java.lang.String trackName) {
    this.trackName = trackName;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getTrackRating() {
    return trackRating;
  }

  /**
   * @param trackRating trackRating or {@code null} for none
   */
  public Tracks setTrackRating(java.lang.Integer trackRating) {
    this.trackRating = trackRating;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public User getUser() {
    return user;
  }

  /**
   * @param user user or {@code null} for none
   */
  public Tracks setUser(User user) {
    this.user = user;
    return this;
  }

  @Override
  public Tracks set(String fieldName, Object value) {
    return (Tracks) super.set(fieldName, value);
  }

  @Override
  public Tracks clone() {
    return (Tracks) super.clone();
  }

}
